// Generates android/app/src/main/res/xml/network_security_config.xml from the build environment.
//   PIN_DOMAINS      comma-separated API hosts to pin (e.g. api.example.com)
//   PIN_SHA256       comma-separated base64 SPKI SHA-256 pins (primary + backup); required with PIN_DOMAINS
//   PIN_EXPIRES      optional pin-set expiration (YYYY-MM-DD); after it the pins are not enforced
//   PIN_TEST_BAD_DOMAINS  CI only: hosts pinned to a wrong key, to prove pinning rejects them
//   DEV_CA_PEM       CI only: path to a self-signed CA trusted for the pinned hosts
//   CAP_DEV_CLEARTEXT=1  emulator/CI builds that talk to a local http API
// Pins are enforced for the app's HTTP requests, which go through the native stack (CapacitorHttp is enabled
// whenever pins are configured; see capacitor.config.ts).
import { copyFileSync, mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..', 'android', 'app', 'src', 'main', 'res');
const list = (v) => (v ?? '').split(',').map((s) => s.trim()).filter(Boolean);
const domains = list(process.env.PIN_DOMAINS);
const pins = list(process.env.PIN_SHA256);
const bad = list(process.env.PIN_TEST_BAD_DOMAINS);
const cleartext = process.env.CAP_DEV_CLEARTEXT === '1';
const ca = process.env.DEV_CA_PEM;

if (domains.length && !pins.length) throw new Error('PIN_DOMAINS needs PIN_SHA256 (primary + backup pin)');
if (pins.some((p) => !/^[A-Za-z0-9+/]{43}=$/.test(p))) throw new Error('PIN_SHA256 entries must be base64 SHA-256 digests');
if (domains.length && pins.length < 2) console.warn('network-config: add a backup pin, or a key rotation will lock users out');
if (process.env.PIN_EXPIRES && !/^\d{4}-\d{2}-\d{2}$/.test(process.env.PIN_EXPIRES)) throw new Error('PIN_EXPIRES must be YYYY-MM-DD');

const rawDir = join(root, 'raw');
rmSync(join(rawDir, 'dev_ca.pem'), { force: true });
if (ca) { mkdirSync(rawDir, { recursive: true }); copyFileSync(ca, join(rawDir, 'dev_ca.pem')); }
const anchors = `<trust-anchors>${ca ? '<certificates src="@raw/dev_ca"/>' : ''}<certificates src="system"/></trust-anchors>`;
const pinSet = (values) => `<pin-set${process.env.PIN_EXPIRES ? ` expiration="${process.env.PIN_EXPIRES}"` : ''}>${values.map((p) => `<pin digest="SHA-256">${p}</pin>`).join('')}</pin-set>`;
const domainXml = (ds) => ds.map((d) => `<domain includeSubdomains="true">${d}</domain>`).join('');
// A wrong (all-zero) pin: connections to these test hosts must fail.
const WRONG = 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=';

const xml = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/network-config.mjs; edit that script, not this file. -->
<network-security-config>
  <base-config cleartextTrafficPermitted="${cleartext}">${anchors}</base-config>
${domains.length ? `  <domain-config cleartextTrafficPermitted="false">${domainXml(domains)}${pinSet(pins)}${anchors}</domain-config>\n` : ''}${bad.length ? `  <domain-config cleartextTrafficPermitted="false">${domainXml(bad)}${pinSet([WRONG])}${anchors}</domain-config>\n` : ''}</network-security-config>
`;
mkdirSync(join(root, 'xml'), { recursive: true });
writeFileSync(join(root, 'xml', 'network_security_config.xml'), xml);
console.log(`network-config: ${domains.length ? `pinned ${domains.join(', ')}` : 'no pins'}${bad.length ? `; wrong pin for ${bad.join(', ')}` : ''}; cleartext ${cleartext ? 'allowed (dev)' : 'off'}`);
