/**
 * Economy Monte-Carlo: plays real RunSim shows with a human timing model, then simulates 60 days for three
 * player archetypes using the real reward, daily, mission, shop and upgrade rules. Output: Markdown report.
 * Usage: npx tsx scripts/economy-sim.ts > ../../docs/ECONOMY_SIMULATION.md
 */
import {
  RunSim, DEFAULT_PARAMS, createRng, computeRunRewards, checkDaily, dailyMissions, applyRunToMission, playerLevelForFans,
  CATALOG, UPGRADES, upgradeCost, applyDailyPacing, type RunSummary, type DailyState, type RunParams,
} from '../src';

/** Gaussian sample (Box–Muller) from a seeded RNG. */
function gauss(rng: () => number): number {
  return Math.sqrt(-2 * Math.log(rng() || 1e-9)) * Math.cos(2 * Math.PI * rng());
}

/** One show by a human who aims at the best moment with timing noise sigmaMs (and sometimes hesitates). */
function playShow(seed: number, params: RunParams, sigmaMs: number): RunSummary {
  const sim = new RunSim(seed, params);
  const rng = createRng(seed ^ 0xa11ce);
  let t = 0;
  while (sim.state === 'active' && t < 20 * 60_000) {
    while (!sim.canTap(t) && sim.state === 'active') { t += 2; sim.advance(t); }
    if (sim.state !== 'active') break;
    let best = t; let err = Infinity;
    for (let x = t; sim.canTap(x); x += 2) {
      const v = sim.view(x); const e = Math.hypot((v.shadowX - v.holeX) / 60, (v.shadowScale - v.holeScale) / 0.35);
      if (e < err) { err = e; best = x; }
    }
    const hesitate = rng() < 0.05; // occasionally the player misses the moment and the round times out
    if (hesitate) { t += 6000; sim.advance(t); continue; }
    t = Math.max(t, Math.round(best + gauss(rng) * sigmaMs));
    sim.advance(t);
    sim.tap(t);
  }
  sim.advance(Number.MAX_SAFE_INTEGER / 2);
  return sim.summary();
}

const ARCHETYPES = [
  { name: 'Rahat (casual)', runsPerDay: 3, sigma: 70, playsDailyChance: 0.6 },
  { name: 'Düzenli (regular)', runsPerDay: 8, sigma: 45, playsDailyChance: 0.9 },
  { name: 'Tutkun (hardcore)', runsPerDay: 20, sigma: 28, playsDailyChance: 1 },
];
const DAYS = 60;
const SAMPLES = 120;

const lines: string[] = [];
const out = (s = '') => lines.push(s);
out('# Economy Simulation (Monte-Carlo)');
out('');
out('Rules in effect: credits = ⌊score/5⌋ + 10·bosses (cap 150/show); full credits for the first 10 shows per day, then 25% ("tired audience"); ≤ 3 show-gems per day; upgrades 600/1500/3000 + 1500/4000; 11 paid cosmetics (300–6000 credits, 15–60 gems).');
out('');
out(`Generated by \`packages/shared/scripts/economy-sim.ts\` with the real game rules (RunSim, rewards, daily streak, missions, shop, upgrades). ${SAMPLES} simulated shows per skill/upgrade level feed a ${DAYS}-day simulation per archetype. Players buy upgrades first, then the cheapest affordable cosmetic. No real money exists in the game.`);
out('');

for (const a of ARCHETYPES) {
  const rng = createRng(a.runsPerDay * 7919);
  // Show outcome distributions per (toleranceLevel, encoreLevel) actually reached by this player.
  const cache = new Map<string, RunSummary[]>();
  const sample = (p: RunParams): RunSummary => {
    const key = `${p.toleranceLevel}/${p.encoreLevel}`;
    if (!cache.has(key)) cache.set(key, Array.from({ length: SAMPLES }, (_, i) => playShow(1000 + i * 37, p, a.sigma)));
    const arr = cache.get(key)!;
    return arr[Math.floor(rng() * arr.length)]!;
  };
  let credits = 0, gems = 0, fans = 0;
  let earnedCredits = 0, spentCredits = 0, earnedGems = 0, spentGems = 0;
  const owned = new Set(CATALOG.filter((c) => c.price === 0).map((c) => c.id));
  const levels: Record<string, number> = { tolerance: 0, encore: 0 };
  let daily: DailyState = { streak: 0, lastClaimDay: null, graceUsed: false };
  const rows: string[] = [];
  let allOwnedDay: number | null = null;
  const scores: number[] = [];
  for (let day = 1; day <= DAYS; day++) {
    if (rng() > a.playsDailyChance) continue;
    const date = new Date(Date.UTC(2026, 0, day)).toISOString().slice(0, 10);
    const d = checkDaily(daily, date);
    if (d.canClaim) { daily = d.next; credits += d.reward.credits; gems += d.reward.gems; earnedCredits += d.reward.credits; earnedGems += d.reward.gems; }
    const missions = dailyMissions(`sim-${a.name}`, date).map((m) => ({ m, p: 0, claimed: false }));
    let gemsToday = 0;
    for (let r = 0; r < a.runsPerDay; r++) {
      const s = sample({ ...DEFAULT_PARAMS, toleranceLevel: levels.tolerance!, encoreLevel: levels.encore! });
      scores.push(s.score);
      const rw = applyDailyPacing(computeRunRewards(s), r, gemsToday);
      gemsToday += rw.gems;
      credits += rw.credits; gems += rw.gems; fans += rw.fans; earnedCredits += rw.credits; earnedGems += rw.gems;
      for (const x of missions) {
        x.p = applyRunToMission(x.m, x.p, s);
        if (!x.claimed && x.p >= x.m.target) { x.claimed = true; credits += x.m.reward; earnedCredits += x.m.reward; }
      }
    }
    // Spend: upgrades (cheapest next level) first, then cosmetics.
    for (;;) {
      const next = UPGRADES.map((u) => ({ id: u.id, cost: upgradeCost(u.id, levels[u.id]!) })).filter((u) => u.cost !== null && u.cost <= credits).sort((x, y) => x.cost! - y.cost!)[0];
      if (next) { credits -= next.cost!; spentCredits += next.cost!; levels[next.id]! += 1; continue; }
      const item = CATALOG.filter((c) => !owned.has(c.id) && (c.currency === 'credits' ? credits : gems) >= c.price).sort((x, y) => x.price - y.price)[0];
      if (item) {
        if (item.currency === 'credits') { credits -= item.price; spentCredits += item.price; } else { gems -= item.price; spentGems += item.price; }
        owned.add(item.id); continue;
      }
      break;
    }
    const allUpgrades = UPGRADES.every((u) => levels[u.id] === u.costs.length);
    if (allOwnedDay === null && owned.size === CATALOG.length && allUpgrades) allOwnedDay = day;
    if ([1, 3, 7, 14, 30, 45, 60].includes(day)) rows.push(`| ${day} | ${playerLevelForFans(fans)} | ${fans} | ${credits} | ${gems} | ${owned.size}/${CATALOG.length} | ${levels.tolerance}/3 · ${levels.encore}/2 |`);
  }
  scores.sort((x, y) => x - y);
  const q = (p: number) => scores[Math.floor(p * (scores.length - 1))];
  out(`## ${a.name} — ${a.runsPerDay} shows/day, timing σ≈${a.sigma} ms`);
  out('');
  out(`Show score: median ${q(0.5)}, p90 ${q(0.9)}, max ${scores.at(-1)}.`);
  out('');
  out('| Day | Player level | Fans | Credits held | Gems held | Cosmetics owned | Upgrades (Steady Hands · Bis!) |');
  out('|---|---|---|---|---|---|---|');
  rows.forEach((r) => out(r));
  out('');
  out(`- Credits earned ${earnedCredits}, spent ${spentCredits} (${Math.round((spentCredits / Math.max(1, earnedCredits)) * 100)}% sunk); gems earned ${earnedGems}, spent ${spentGems}.`);
  out(`- Everything owned on day: ${allOwnedDay ?? `not within ${DAYS} days`}.`);
  out('');
}
out('## Reading the results');
out('');
out('- **Progression speed**: compare "Everything owned" across archetypes — casual players should still have goals after weeks, hardcore players finish the catalogue in weeks, not days.');
out('- **Inflation**: once everything is owned, credits only accumulate (no further sinks). The "Credits held" column at day 45–60 shows how much unspendable currency builds up; this is the signal for adding new sinks (seasonal cosmetics) before it grows large.');
out('- Revives (gems) are not used by the bots above; real players spending gems on revives lowers gem balances further.');
console.log(lines.join('\n'));
